# Generated by Django 5.1 on 2024-08-14 11:34

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('specialty', models.CharField(max_length=255)),
                ('available_days', models.JSONField()),
                ('location', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=50)),
                ('marital_status', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=20)),
                ('primary_language', models.CharField(max_length=50)),
                ('referred_by_physician', models.BooleanField(default=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('reason_for_appointment', models.TextField()),
                ('interpretation_services', models.BooleanField(default=False)),
                ('visit_type', models.CharField(choices=[('In-office', 'In-office'), ('Virtual', 'Virtual'), ("Doesn't matter", "Doesn't matter")], max_length=20)),
                ('preferred_day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('First available', 'First available')], max_length=20)),
                ('preferred_time', models.CharField(choices=[('AM', 'AM'), ('PM', 'PM'), ('First available', 'First available')], max_length=20)),
                ('payment_method', models.CharField(choices=[('Insurance', 'Insurance'), ('Out-of-pocket', 'Out-of-pocket')], max_length=50)),
                ('insurance_company', models.CharField(blank=True, max_length=255, null=True)),
                ('insurance_product_type', models.CharField(blank=True, max_length=50, null=True)),
                ('insurance_policy_number', models.CharField(blank=True, max_length=50, null=True)),
                ('insurance_policy_holder', models.CharField(blank=True, max_length=50, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.doctor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
